# TASCA M3 T01

En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris.

Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”.

Per a obtenir informació del dataset pots consultar el següent enllaç:

-> sklearn.datasets.load_iris 

In [9]:
# Intento cargar la librería sklearn.datasets con el código: "!pip install sklearn"
# Lo intento tanto en jupiter como en la terminal, pero me da error. 
# Teniendo en cuenta el error que me indica, introduzco el siguiento códido que resulta funcionar.
!pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 5.0 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 4.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 3.0 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip


In [17]:
# Una vez que he importado la  les dades de la librería sklearn.datasets, 
# me dispongo a descargar el conjunt de datos denominados "iris".

from sklearn.datasets import load_iris
data = load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

Como me dice que Iris está conformada por varios conjuntos de datos, dentro de ellos: 
- el array denominado: “data” 
- el array denominado:“target”
- la lista: “feature_names” 
- la lista: “target_names”

Voy a descargarme cada uno de ellos para ver que pinta tienen:


In [14]:
# Como el array "data" está dentro de la "data" global que contiene todos los datos, 
# para distinguirlos al seguundo lo llamo "data2" 
data2=data.data
print(data2)

# veo que data2 es una matriz de cuatro columnas y muchas filas de floats.

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
target=data.target
print(target)

# Target en realidad es una lista con muchos datos, pero solo hay tres tipos de dados diferentes.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [18]:
feature_names=data.feature_names
print(feature_names)

# feature_names es una lista con cuatro elementos: ancho y largo de pétalos y sépalos
# presumo que van a ser los nombres de las columnas

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
target_names=data.target_names
print(target_names)

# Es una lista con tres elementos,
# presumo que son los nombres de las tres categorías de datos que componen la lista "target"

['setosa' 'versicolor' 'virginica']


## Exercici 1
Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [13]:
print(data2[:9])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]


In [20]:
print(target[:9])

[0 0 0 0 0 0 0 0 0]


## Exercici 2
Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [79]:
# En esta concatenación estoy intentando agregar la lista "target" como columna a la matriz "data2"
# Primero debo conseguir convertir la lista en una matriz columna mediante el uso del operador transponer (T)
# Para concatenar las cuarta columba uso el parámetro axis=1 para indicarle que es conlumna,

data3=np.concatenate((data2, np.array([target]).T), axis=1)
print(data3)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [33]:
# Mostra els 5 primers registres:
print(data3[:4])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]]


## Exercici 3
- Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). 
- Mostra els resultats amb dos decimals.



In [52]:
# Primero extrigo las columnas de Longitud de sépalos y Longitud de sépalos, 
# Son las columnas 1ª y 3ª de la matriz data3

LongSep = data3[:,0]
LongPet = data3[:,2]

print(LongSep)
print(LongPet)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.4 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 

In [72]:
# La media de cada columna la calculo con la función columna.mean()
# La desviación típica de cada columna la calculo con la función columna.std()
# Para que me redondee a 2 decimales aplico la fución ==> round(dato, nº decimales)
# Esta función lo que hace es redondear toda la cola de decimales a los decimales que le pidamos.

MedLongSep=round(LongSep.mean(), 2)
MedLongPet=round(LongPet.mean(), 2)
StdLongSep=round(LongSep.std(), 2)
StdLongPet=round(LongPet.std(), 2)

print("La MEDIA de la longitud del SÉPALO es:", MedLongSep)
print("La MEDIA de la longitud del PÉTALO es:", MedLongPet)
print("La DESVIACIÓN TÍPICA de la longitud del SÉPALO es:", StdLongSep)
print("La DESVIACIÓN TÍPICA de la longitud del PÉTALO es:", StdLongPet)

La MEDIA de la longitud del SÉPALO es: 5.84
La MEDIA de la longitud del PÉTALO es: 3.76
La DESVIACIÓN TÍPICA de la longitud del SÉPALO es: 0.83
La DESVIACIÓN TÍPICA de la longitud del PÉTALO es: 1.76


In [76]:
# Si lo que quiero es que me de los decimilaes reales sin redondear, uso la fución ==> format
# En este caso le voy a pedir que me de tres decimales para comprobar que le redondeo anterior está OK.

print("La MEDIA de la longitud del SÉPALO es:", "{:.3f}".format(LongSep.mean()))
print("La MEDIA de la longitud del PÉTALO es:", "{:.3f}".format(LongPet.mean()))
print("La DESVIACIÓN TÍPICA de la longitud del SÉPALO es:", "{:.3f}".format(LongSep.std()))
print("La DESVIACIÓN TÍPICA de la longitud del PÉTALO es:", "{:.3f}".format(LongPet.std()))

La MEDIA de la longitud del SÉPALO es: 5.843
La MEDIA de la longitud del PÉTALO es: 3.758
La DESVIACIÓN TÍPICA de la longitud del SÉPALO es: 0.825
La DESVIACIÓN TÍPICA de la longitud del PÉTALO es: 1.759


## Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [98]:
# Primero tengo que importar la función ramdom de numpy
from numpy import random

# Por pueba error he vistoa que para poder conseguir números aleatorios de la matriz datos3==> 
# primero he de transformar esa matriz 2-D en 1-D
# Lo hago con fución concatenate ()

data3to1D = np.concatenate(data3)

# Le pido los 20 numereos aletorios con la función random.choice(), definiéndole que quiero 20 resultados.
aleatorios = random.choice(data3to1D, 20)

print(aleatorios)

[2.  5.9 0.  4.7 0.  0.2 1.  2.  5.7 4.4 4.5 3.6 1.5 5.4 0.3 3.3 6.7 3.
 6.7 2.7]


## Exercici 5
Crea una matriu que mostri: 

• La mitjana de cada característica per espècie. 

• La desviació estàndard de cada característica per espècie.

In [209]:
# las especies están definidas en la columna target_name, que es la 5ª columna de data3. 
# Hay tres especies diferentes.
# Es una matriz (3_especies, 4_características)

# Primero conseguir los datos únicos de las espcecies, de la columna 5, agrupados

especies=np.unique(data3[:,4])

# Imprimo para comprobar que está ok
print("las especies de esta tabla son:",especies)

# Identifico la matriz en la que están los datos sobre los que hacer los cálculos (las primeras cuatro columnas)
mediciones=data3[:, :4]


# Creo unas listas vacías de media y desviación típica, que vayan acumulando los datos del for posterior
medias=[]
desviaciones=[]

# Hacer un for que vaya pasando por las esepecies únicas y calculando las medias y deviaciones de cada columna.

for i in especies: 
    
    # Calculo la media de cada especie a lo largo de las filas para cada parámetro
    # Para ello le tengo que decir que me haga el cálculo de las columnas de 0 a 3 mientras que ==>
    # ==> el valor de la columna target sea =i
    media_por_especie = np.round(np.mean(data3[target==i, :4], axis=0),2)
    
    # Agrego las medias conseguidas a la lista vacía de medias
    medias.append(media_por_especie)
    
    # Calculo la desviación a lo largo de las filas para cada parámetro 
    desviacion_por_especie = np.round(np.std(data3[target==i, :4], axis=0),2)
    
    # Agrego las desviaciones conseguidas a la lista vacía de desviaciones
    desviaciones.append(desviacion_por_especie)


# Cuando se termine el for imprimir lo que se ha ido acumulando en las listas vacías.    
# Como me da unos arrays muy feos, convierto ambas listas en dos matrices Numpy
medias = np.array(medias)
desviaciones = np.array(desviaciones)  
print()    
print("La matriz de medias es:\n\n", medias)
print()
print("La matriz de desviaciones es:\n\n",desviaciones)

   

las especies de esta tabla son: [0. 1. 2.]

La matriz de medias es:

 [[5.01 3.43 1.46 0.25]
 [5.94 2.77 4.26 1.33]
 [6.59 2.97 5.55 2.03]]

La matriz de desviaciones es:

 [[0.35 0.38 0.17 0.1 ]
 [0.51 0.31 0.47 0.2 ]
 [0.63 0.32 0.55 0.27]]


## Exercici 6
• Calcula la quantitat de mostres per espècie.

• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [212]:
# Calcula la quantitat de mostres per espècie.
# Utilizo esta fórmula que encuentro en internet y me permite hacer el contaje sobre la columna lista target
# Le pongo delante np.array() para que me lo devuelva como matriz para ver bien los datos.
np.array(np.unique(target, return_counts=True))

array([[ 0,  1,  2],
       [50, 50, 50]])

In [221]:
# Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"
# Es decir, cuál es la espicie que tiene el mayor valor de media en la longitud de sepalos (columna 0)

for n in medias[0]:
   
    media_sepalo_max = np.max(medias) 
    print(media_sepalo_max)
 


6.59
6.59
6.59
6.59


## Exercici 7
• Calcula la matriu de correlació entre les variables.

• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

• Troba la mostra amb els pètals més grans.

In [160]:
# Calcular la matriz de correlación:
# Aplico la función np.corrcoef() sobre data 2 o data3[:, :4], que es donde están las mediciones.
# Para indicarle que las variables están en las columnas, le aporto el argumento rowvar=False.

matriz_correlación = np.corrcoef(data3[:, :4], rowvar=False)

print("La matriz de correlaciónes:\n", matriz_correlación)

La matriz de correlaciónes:
 [[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [165]:
# Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho.

# Aislo la columla longitud de pétalos (3ª columna para tarbajar con ella)
longitud_petalos = data3[:, 2]

# Calculo la media de la longitud de pétalos
media_longitud_petalos = np.mean(longitud_petalos)

# Filtrar valores superiores a la media
valores_superan_media = longitud_petalos[longitud_petalos > media_longitud_petalos]

# Mostrar los valores filtrados
print("Los valores de longitud de pétalos superiores a la media son:\n", valores_superan_media)


Los valores de longitud de pétalos superiores a la media son:
 [4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]


In [179]:
# Troba la mostra amb els pètals més grans
 
# En la variable longitud_petalos que ya he definido antes 
# busco el dato del pétalo más largo con la función: np.max

print()
print ("El pétalo más largo de la muestra mide:", np.max(longitud_petalos),"cm")
print()

# Busco el indice al que se corresponde ese dato del pétalo más largo con el argumento: np.argmax
indice_petal_mas_largo = np.argmax(longitud_petalos)   

print ("El índice de la muestra con el pétalo más largo es:", indice_petal_mas_largo)
print()

# Le pido que me imprima toda la fila de la muestra con el pétalo más largo: 

muestra_petal_mas_largo = data3[indice_petal_mas_largo]

print("La muestra con el pétalo más largo tiene los siguientes datos:", muestra_petal_mas_largo)
print()


El pétalo más largo de la muestra mide: 6.9 cm

El índice de la muestra con el pétalo más largo es: 118

La muestra con el pétalo más largo tiene los siguientes datos: [7.7 2.6 6.9 2.3 2. ]



## Exercici 8
Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [206]:
# Tengo que crear dos listas de 3 elementos, 
# - La primera lista tendrá las medias de longitud de los PÉTALOS de cada especie.
# - La segunda lista tendrá las medias de longitud de los SÉPALOS de cada especie.
# Tengo que comparar los dos datos de cada especie
# Imprimir la especie que tenga la mayor diferencia.

# Por lo que investigo, debería utilizar máscaras booleanas, que no sé lo que son.

# Extraer las columnas relevantes (longitud de sépalos y pétalos y especies)
longitud_sepalos = data3[:, 0]
longitud_petalos = data3[:, 2]
especies = data3[:, 4]

# Calcular la longitud media de sépalos y pétalos por especie
longitud_sepalos_medias = []
longitud_petalos_medias = []

for especie in np.unique(especies):
    mask = especies == especie
    longitud_sepalos_media = np.mean(longitud_sepalos[mask])
    longitud_petalos_media = np.mean(longitud_petalos[mask])
    longitud_sepalos_medias.append(longitud_sepalos_media)
    longitud_petalos_medias.append(longitud_petalos_media)

print(longitud_sepalos_medias)
print(longitud_petalos_medias)

# Calcular la diferencia entre las longitudes de sépalos y pétalos
diferencias = np.abs(np.array(longitud_sepalos_medias) - np.array(longitud_petalos_medias))

# Encontrar la especie con la mayor diferencia
indice_especie_max_dif = np.argmax(diferencias)
especie_max_dif = np.unique(especies)[indice_especie_max_dif]

# Imprimir la especie con la mayor diferencia
print("La especie con la mayor diferencia entre longitud media de sépalos y pétalos es:", especie_max_dif)

[5.006, 5.936, 6.587999999999998]
[1.4620000000000002, 4.26, 5.5520000000000005]
La especie con la mayor diferencia entre longitud media de sépalos y pétalos es: 0.0
